<?php
/*
 |--------------------------------------------------------------------------
 | Prologue configuration (edit this section for web hosting/web servers)
 |--------------------------------------------------------------------------
 | If you are using Docker, do NOT edit this file. Use docker-compose env vars.
 */


$CONFIG_DB_HOST = 'localhost'; //in most cases you can leave this as localhost
$CONFIG_DB_USER = 'example';
$CONFIG_DB_PASS = 'example';
$CONFIG_DB_NAME = 'example';

$CONFIG_APP_URL = 'https://example.com'; //example: https://example.com or https://prologue.example.com
$CONFIG_APP_SUBFOLDER = ''; //leave this blank unless running in a subfolder. if using a subfolder like https://example.com/prologue the value of this would be the name of the subfolder in this case prologue

$CONFIG_STORAGE_FILESYSTEM_ROOT = '/home/example/storage';
$CONFIG_LOG_DIRECTORY = '/home/example/storage/logs';
$CONFIG_DATABASE_SCHEMA_SQL = <<<'SQL'
-- Paste the schema SQL here.
-- For example, copy the value of $CONFIG_DATABASE_SCHEMA_SQL from config.php.
SQL;

$CONFIG_CSRF_SECRET = 'change-this-to-random-64-chars';
$CONFIG_APP_NAME = 'Prologue';


/*
 |--------------------------------------------------------------------------
 | Internal resolution (env vars override file values)
 |--------------------------------------------------------------------------
 */

define('APP_NAME', $CONFIG_APP_NAME);
$versionConfig = require __DIR__ . '/../../version.php';
define('APP_VERSION', isset($versionConfig['app_version']) ? (string)$versionConfig['app_version'] : '0.0.0');

define('DB_HOST', getenv('DB_HOST') ?: $CONFIG_DB_HOST);
define('DB_USER', getenv('DB_USER') ?: $CONFIG_DB_USER);
define('DB_PASS', getenv('DB_PASS') ?: $CONFIG_DB_PASS);
define('DB_NAME', getenv('DB_NAME') ?: $CONFIG_DB_NAME);

$scheme = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
$host = $_SERVER['HTTP_HOST'] ?? 'localhost:8088';

$appBasePath = trim((string)(getenv('APP_BASE_PATH') ?: $CONFIG_APP_SUBFOLDER), " \t\n\r\0\x0B/");
if ($appBasePath === '') {
	$scriptName = (string)($_SERVER['SCRIPT_NAME'] ?? '');
	$detectedBasePath = $scriptName !== '' ? trim((string)dirname($scriptName), " \t\n\r\0\x0B/") : '';
	$appBasePath = $detectedBasePath;
}
define('APP_BASE_PATH', $appBasePath);

$appUrlFromEnv = trim((string)(getenv('APP_URL') ?: $CONFIG_APP_URL));
if ($appUrlFromEnv !== '') {
	define('APP_URL', rtrim($appUrlFromEnv, '/'));
} else {
	$basePathSuffix = APP_BASE_PATH !== '' ? '/' . APP_BASE_PATH : '';
	define('APP_URL', rtrim($scheme . '://' . $host . $basePathSuffix, '/'));
}

$storageRootFromEnv = trim((string)(getenv('STORAGE_FILESYSTEM_ROOT') ?: $CONFIG_STORAGE_FILESYSTEM_ROOT));
define('STORAGE_FILESYSTEM_ROOT', rtrim($storageRootFromEnv, '/'));

$logDirFromEnv = trim((string)(getenv('LOG_DIRECTORY') ?: $CONFIG_LOG_DIRECTORY));
define('APP_LOG_DIRECTORY', $logDirFromEnv !== '' ? $logDirFromEnv : (STORAGE_FILESYSTEM_ROOT . '/logs'));

$databaseSchemaSqlFromEnv = (string)(getenv('DATABASE_SCHEMA_SQL') ?: $CONFIG_DATABASE_SCHEMA_SQL);
if (trim($databaseSchemaSqlFromEnv) !== '') {
	define('DATABASE_SCHEMA_SQL', $databaseSchemaSqlFromEnv);
}

function base_url($path = '') {
	$base = APP_URL;
	if (PHP_SAPI !== 'cli' && isset($_SERVER['HTTP_HOST']) && getenv('APP_URL') === false) {
		$requestScheme = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
		$basePathSuffix = APP_BASE_PATH !== '' ? '/' . APP_BASE_PATH : '';
		$base = $requestScheme . '://' . $_SERVER['HTTP_HOST'] . $basePathSuffix;
	}

	if ($path === '' || $path === '/') {
		return $base;
	}

	return rtrim($base, '/') . '/' . ltrim($path, '/');
}
define('CSRF_SECRET', $CONFIG_CSRF_SECRET);